### ISSUE TITLE
Alignment Issue with RGB Image

### ISSUE THREAD

**Issue by FishAndWasabi** [82magnolia/n_imagenet#6]
Dear author,

Thanks for your great work! 

We have noticed that the provided event image is not fully aligned with the original RGB image, with an offset in the upper part.

Is this phenomenon considered normal? Are there any methods to address this issue?

![cb613f43-a454-493e-bea2-7f6dc3994145](https://github.com/82magnolia/n_imagenet/assets/45028025/4d3c4067-f7bb-4ec3-9726-4cc3bfa22c52)

![6684cc5c-080d-4e8a-95aa-8c1b0a121e01](https://github.com/82magnolia/n_imagenet/assets/45028025/79b1d3b6-2783-4d91-a51a-2c1c9d282a18)

**Comment by 82magnolia** [comment]
Hi, as we used a fixed size monitor with a camera undergoing fronto-parallel movements, there were some image regions in the original N-ImageNet dataset that were cropped off. Thus the events and original images are not perfectly aligned.

We haven't tried this out, but I feel you could try establishing pixel-level alignments by i) obtaining event-to-image conversions using methods such as E2Vid(https://github.com/uzh-rpg/rpg_e2vid), and ii) estimating the homography between the reconstructed image and the original ImageNet image using local feature matching + RANSAC (https://docs.opencv.org/3.4/d1/de0/tutorial_py_feature_homography.html). Since the monitor and event camera used during data acquisition were almost perfectly parallel, homography estimation would yield reasonably accurate pixel-level alignments.
